services:
  web:
    build: .
    container_name: intranet-container
    
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate &&
        python manage.py shell < init_super_user.py &&
        python manage.py runserver 0.0.0.0:8000"
        