# Generated by Django 6.0.4 on 2026-04-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=120)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('ejemplares_totales', models.PositiveIntegerField(default=1)),
                ('ejemplares_disponibles', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['titulo'],
                'permissions': [('puede_gestionar_biblioteca', 'Puede gestionar libros y prestamos')],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('DEV', 'Devuelto'), ('ATR', 'Atrasado')], default='ACT', max_length=3)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_biblioteca', to='academico.expedienteestudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.libro')),
            ],
            options={
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]

