# Generated by Django 6.0.4 on 2026-04-23 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJ', 'Baja'), ('MED', 'Media'), ('ALT', 'Alta'), ('CRI', 'Critica')], default='MED', max_length=3)),
                ('estado', models.CharField(choices=[('ABI', 'Abierto'), ('PRO', 'En Proceso'), ('RES', 'Resuelto'), ('CER', 'Cerrado')], default='ABI', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('puede_gestionar_soporte', 'Puede gestionar tickets de soporte')],
            },
        ),
    ]
