# Generated by Django 6.0.4 on 2026-04-19 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ABI', 'Abierto'), ('PRO', 'En proceso'), ('RES', 'Resuelto'), ('CER', 'Cerrado')], default='ABI', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'permissions': [('puede_gestionar_tickets', 'Puede gestionar todos los tickets'), ('puede_atender_tickets', 'Puede atender tickets asignados')],
            },
        ),
    ]

