# Generated by Django 6.0.4 on 2026-04-23 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte_it', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('puede_gestionar_soporte', 'Puede gestionar tickets de soporte')]},
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('BAJ', 'Baja'), ('MED', 'Media'), ('ALT', 'Alta'), ('CRI', 'Critica')], default='MED', max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('ABI', 'Abierto'), ('PRO', 'En Proceso'), ('RES', 'Resuelto'), ('CER', 'Cerrado')], default='ABI', max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
