# Generated by Django 6.0.4 on 2026-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('DOC', 'Docente'), ('ADM', 'Administrativo'), ('SER', 'Servicios')], max_length=3)),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
            ],
            options={
                'permissions': [('puede_gestionar_rrhh', 'Puede editar datos de empleados')],
            },
        ),
    ]
